/* 
 * Copyright (C) 2018 Suzn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.sujan.lms.ui.dashboard;

import com.sujan.lms.bll.BookBLL;
import com.sujan.lms.common.exception.UnknownException;
import com.sujan.lms.common.widget.Alert;
import com.sujan.lms.common.entity.book.BookInfo;
import com.sujan.lms.common.entity.user.UserInfo;
import com.sujan.lms.common.exception.CorruptedDataException;
import com.sujan.lms.common.exception.MissingFileException;
import com.sujan.lms.common.exception.ReadWriteException;
import com.sujan.lms.common.exception.RecordNotFoundException;
import com.sujan.lms.common.params.BookParams;
import com.sujan.lms.ui.login.Login;
import com.sujan.lms.common.util.Logy;
import com.sujan.lms.ui.login.UserRegisterDialog;
import java.rmi.NotBoundException;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Suzn
 */
public class GuestDashboard extends javax.swing.JFrame {

    /**
     * Creates new form GuestDashboard
     *
     */
    public GuestDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginIconPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registerIconPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchControlPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Knowledgica - Library Management System");
        setExtendedState(6);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon.png")));
        setMinimumSize(new java.awt.Dimension(780, 620));
        setPreferredSize(new java.awt.Dimension(780, 620));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(39, 26, 252));
        topPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        titlePanel.setBackground(new java.awt.Color(39, 26, 252));
        titlePanel.setPreferredSize(new java.awt.Dimension(508, 125));
        titlePanel.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel2.setBackground(new java.awt.Color(39, 26, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 125));

        jPanel1.setBackground(new java.awt.Color(39, 26, 252));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Knowledgica");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        logo.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        titlePanel.add(jPanel2);

        loginPanel.setBackground(new java.awt.Color(39, 26, 252));
        loginPanel.setPreferredSize(new java.awt.Dimension(370, 125));
        loginPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 20, 30));

        loginIconPanel.setBackground(new java.awt.Color(39, 26, 252));

        loginButton.setBackground(new java.awt.Color(255, 204, 255));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginButton.setToolTipText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.setContentAreaFilled(false);
        loginButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1x.png"))); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginIconPanelLayout = new javax.swing.GroupLayout(loginIconPanel);
        loginIconPanel.setLayout(loginIconPanelLayout);
        loginIconPanelLayout.setHorizontalGroup(
            loginIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginIconPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginIconPanelLayout.setVerticalGroup(
            loginIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPanel.add(loginIconPanel);

        registerIconPanel.setBackground(new java.awt.Color(39, 26, 252));

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        registerButton.setToolTipText("register");
        registerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButton.setContentAreaFilled(false);
        registerButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        registerButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register1x.png"))); // NOI18N
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerIconPanelLayout = new javax.swing.GroupLayout(registerIconPanel);
        registerIconPanel.setLayout(registerIconPanelLayout);
        registerIconPanelLayout.setHorizontalGroup(
            registerIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerIconPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerIconPanelLayout.setVerticalGroup(
            registerIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPanel.add(registerIconPanel);

        titlePanel.add(loginPanel);

        topPanel.add(titlePanel);

        controlPanel.setBackground(new java.awt.Color(39, 26, 252));
        controlPanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(39, 26, 252));
        searchPanel.setPreferredSize(new java.awt.Dimension(349, 50));

        searchControlPanel.setBackground(new java.awt.Color(39, 26, 252));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        searchTextField.setBackground(new java.awt.Color(39, 26, 252));
        searchTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchTextField.setToolTipText("Search for title, publisher, author..");
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        searchTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        searchTextField.setMinimumSize(new java.awt.Dimension(200, 15));
        searchTextField.setPreferredSize(new java.awt.Dimension(200, 15));
        searchTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                System.out.println(text);
                if (text.trim().length() == 0) {
                    ((TableRowSorter<TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((TableRowSorter<TableModel>)table.getRowSorter()).setRowFilter(RowFilter.regexFilter("^(?i)" + text));
                }
                table.repaint();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                if (text.trim().length() == 0) {
                    ((TableRowSorter<TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((TableRowSorter<TableModel>)table.getRowSorter()).setRowFilter(RowFilter.regexFilter("^(?i)" + text));
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                //not needed: throw new UnsupportedOperationException("Not supported yet.");
            }
        });

        javax.swing.GroupLayout searchControlPanelLayout = new javax.swing.GroupLayout(searchControlPanel);
        searchControlPanel.setLayout(searchControlPanelLayout);
        searchControlPanelLayout.setHorizontalGroup(
            searchControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchControlPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchControlPanelLayout.setVerticalGroup(
            searchControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchControlPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(searchControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        searchPanel.add(searchControlPanel);

        controlPanel.add(searchPanel, java.awt.BorderLayout.CENTER);

        topPanel.add(controlPanel);

        rootPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.CardLayout(5, 5));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn(BookParams.ACCESSION_NO.toUpperCase());
        tableModel.addColumn(BookParams.TITLE.toUpperCase());
        tableModel.addColumn(BookParams.SUBJECT.toUpperCase());
        tableModel.addColumn(BookParams.AUTHOR.toUpperCase());
        tableModel.addColumn(BookParams.PUBLISHER.toUpperCase());
        tableModel.addColumn(BookParams.EDITION.toUpperCase());
        tableModel.addColumn(BookParams.ISBN.toUpperCase());
        tableModel.addColumn(BookParams.SHELF_NO.toUpperCase());
        tableModel.addColumn("Available".toUpperCase());
        table.setModel(tableModel);
        table.setRowHeight(24);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);
        jScrollPane1.setViewportView(table);

        centerPanel.add(jScrollPane1, "card2");

        rootPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel1.setText("Developed by: Sujan Parajuli");
        bottomPanel.add(jLabel1);

        rootPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(rootPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadTableData();
    }//GEN-LAST:event_formWindowOpened

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        Logy.d("Register button clicked");
        UserRegisterDialog userRegisterDialog = new UserRegisterDialog(this, true);
        userRegisterDialog.setItemAddedListener((UserInfo user) -> {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        });
        userRegisterDialog.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginIconPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerIconPanel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel searchControlPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable table;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        SwingUtilities.invokeLater(() -> {

            try {
                fillTableData(BookBLL.getAllBook());
            } catch (CorruptedDataException | MissingFileException | ReadWriteException
                    | RecordNotFoundException | UnknownException | NotBoundException ex) {
                Logy.e(ex);
                Alert.showError(this, ex.getMessage());
            }

        });

    }

    private void fillTableData(List<BookInfo> bookInfoList) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) table.getModel();
        int numOfColumn = defaultTableModel.getColumnCount();

        bookInfoList.stream().forEach((bookInfo) -> {
            Object[] object;
            object = new Object[numOfColumn + 1]; //+1 for id
            object[0] = bookInfo.getId();
            object[1] = bookInfo.getTitle();
            object[2] = bookInfo.getSubject().getTitle();
            object[3] = bookInfo.getAuthor().getTitle();
            object[4] = bookInfo.getPublisher().getTitle();
            object[5] = bookInfo.getEdition();
            object[6] = bookInfo.getIsbn();
            object[7] = bookInfo.getShelfNo().getLocation();
            object[8] = bookInfo.getAvailableCopies() > 0;

            defaultTableModel.addRow(object);
        });

    }

}
