/* 
 * Copyright (C) 2018 Suzn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.sujan.lms.ui.book.author;

import com.sujan.lms.action.AuthorListener;
import com.sujan.lms.bll.AuthorBLL;
import com.sujan.lms.common.widget.Alert;
import com.sujan.lms.common.entity.author.Author;
import com.sujan.lms.common.entity.user.UserInfo;
import com.sujan.lms.common.params.AuthorParams;
import com.sujan.lms.ui.BaseUserPanel;
import com.sujan.lms.common.util.Logy;
import com.sujan.lms.util.Utils;
import com.sujan.lms.view.BookView;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suzn
 */
public final class BookAuthorPanel extends BaseUserPanel
        implements BookView<Author>, AuthorListener {

    private List<Author> authorList;
    private final UserInfo userInfo;

    /**
     * Creates new form BookAuthorPanel
     *
     * @param userInfo
     */
    public BookAuthorPanel(UserInfo userInfo) {
        initComponents();
        this.userInfo = userInfo;
        setupUserView(userInfo);
        authorList = new ArrayList<>();
        this.loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        centerSubPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addBookAuthorButton = new javax.swing.JButton();
        updateBookAuthorButton = new javax.swing.JButton();
        deleteBookAuthorButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(249, 249, 249));
        searchPanel.setPreferredSize(new java.awt.Dimension(367, 70));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        searchPanel.setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_blue.png"))); // NOI18N

        searchTextField.setBackground(new java.awt.Color(249, 249, 249));
        searchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTextField.setToolTipText("Search for title, publisher, author..");
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(39, 26, 252)));
        searchTextField.setMinimumSize(new java.awt.Dimension(200, 15));
        searchTextField.setOpaque(false);
        searchTextField.setPreferredSize(new java.awt.Dimension(200, 15));
        searchTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                System.out.println(text);
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
                table.repaint();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                //not needed: throw new UnsupportedOperationException("Not supported yet.");
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        searchPanel.add(jPanel2);

        jPanel4.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        centerSubPanel.setLayout(new java.awt.CardLayout());

        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn(AuthorParams.ID.toUpperCase());
        tableModel.addColumn(AuthorParams.TITLE.toUpperCase());
        tableModel.addColumn(AuthorParams.CONTACT.toUpperCase());
        table.setModel(tableModel);
        table.setRowHeight(26);
        table.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(table);
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> rowSorter = new javax.swing.table.TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);

        centerSubPanel.add(jScrollPane1, "card2");

        jPanel4.add(centerSubPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jPanel3.setOpaque(false);

        addBookAuthorButton.setText("Add New");
        addBookAuthorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBookAuthorButton.setPreferredSize(new java.awt.Dimension(80, 40));
        addBookAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookAuthorButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addBookAuthorButton);

        updateBookAuthorButton.setText("Update");
        updateBookAuthorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBookAuthorButton.setPreferredSize(new java.awt.Dimension(80, 40));
        updateBookAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookAuthorButtonActionPerformed(evt);
            }
        });
        jPanel3.add(updateBookAuthorButton);

        deleteBookAuthorButton.setText("Delete");
        deleteBookAuthorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBookAuthorButton.setPreferredSize(new java.awt.Dimension(80, 40));
        deleteBookAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookAuthorButtonActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBookAuthorButton);

        bottomPanel.add(jPanel3);

        jPanel4.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.add(jPanel4, "card2");

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookAuthorButtonActionPerformed
        BookAuthorInsertDialog bookAuthorInsertDialog = new BookAuthorInsertDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        bookAuthorInsertDialog.setItemAddedListener((Author author) -> {
            appendAuthorData(author);
        });
        bookAuthorInsertDialog.setVisible(true);
    }//GEN-LAST:event_addBookAuthorButtonActionPerformed

    private void updateBookAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookAuthorButtonActionPerformed
        int row = table.getSelectedRow();
        if (row > -1) {
            Author s = getBeanFromRow(table.getRowSorter().convertRowIndexToModel(row));
            if (s != null) {
                BookAuthorUpdateDialog bookAuthorUpdateDialog = new BookAuthorUpdateDialog((JFrame) SwingUtilities.getWindowAncestor(this),
                        true, s);
                bookAuthorUpdateDialog.setItemUpdatedListener((Author author) -> {
                    updateAuthorData(author, row);
                });
                bookAuthorUpdateDialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_updateBookAuthorButtonActionPerformed

    private void deleteBookAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookAuthorButtonActionPerformed
        if (Utils.isTableRowSelected(table)) {
            if (Alert.showDeleteConfirmDialog(this) == JOptionPane.YES_OPTION) {
                int row = table.getSelectedRow();
                int id = Utils.getIdFromTable(table, table.getRowSorter().convertRowIndexToModel(row));
                try {
                    Author author = new Author(id);
                    AuthorBLL.deleteAuthor(author);
                    removeAuthorData(author, row);
                } catch (Exception ex) {
                    Logy.e(ex);
                    Alert.showError(this, ex.getMessage());
                }
            }

        }
    }//GEN-LAST:event_deleteBookAuthorButtonActionPerformed

    @Override
    public final void loadTableData() {

        if (authorList == null || authorList.isEmpty()) {
            Logy.d("Loading author from file for first Time");
            try {
                authorList = AuthorBLL.getAllAuthor();
            } catch (Exception ex) {
                Logy.e(ex);
                Alert.showError(this, ex.getMessage());
                return;
            }

        } else {
            Logy.d("author already loaded");
        }

        this.fillTableData(authorList);

    }

    /**
     *
     * @param authorInfoList
     */
    @Override
    public final void fillTableData(List<Author> authorInfoList) {

        authorInfoList.stream().forEach((authorInfo) -> {
            addAuthorRowData(authorInfo);
        });

    }

    public void addAuthorRowData(Author author) {
        ((DefaultTableModel) table.getModel()).insertRow(0, new Object[]{
            author.getId(),
            author.getTitle(),
            author.getContact()
        });
    }

    private void updateAuthorData(Author s, int row) {
        for (Author author : authorList) {
            if (author.getId() == s.getId()) {
                author.setTitle(s.getTitle());
                author.setContact(s.getContact());
                break;
            }
        }

        updateAuthorRowData(s, row);
    }

    private void updateAuthorRowData(Author author, int row) {
        ((DefaultTableModel) table.getModel()).setValueAt(author.getTitle(), row, 1);
        ((DefaultTableModel) table.getModel()).setValueAt(author.getContact(), row, 2);
    }

    private Author getBeanFromRow(int row) {
        int id = (int) table.getModel().getValueAt(row, 0);
        return authorList.stream()
                .filter((author) -> author.getId() == id)
                .findFirst()
                .orElse(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookAuthorButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerSubPanel;
    private javax.swing.JButton deleteBookAuthorButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable table;
    private javax.swing.JButton updateBookAuthorButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onAuthorDataChanged(Author a) {
        appendAuthorData(a);
    }

    private void appendAuthorData(Author author) {
        authorList.add(author);
        addAuthorRowData(author);
    }

    @Override
    protected void setupAdminView() {
    }

    @Override
    protected void setupLibrarianView() {
        this.deleteBookAuthorButton.setVisible(false);
    }

    @Override
    protected void setupMemberView() {
        addBookAuthorButton.setVisible(false);
        updateBookAuthorButton.setVisible(false);
        this.deleteBookAuthorButton.setVisible(false);
    }

    @Override
    public void onAuthorDataRemoved(Author a) {
        for (Author auth : authorList) {
            if (auth.getId() == a.getId()) {
                authorList.remove(auth);
                break;
            }
        }

    }

    private void removeAuthorData(Author a, int row) {
        onAuthorDataRemoved(a);
        ((DefaultTableModel) table.getModel()).removeRow(row);
    }

}
